
export class Product {
    constructor(public id: number,
                public nom: string,
                public images: Array<any>,
                public image1: string,
                public image2: string,
                public image3: string,
                public image4: string,
                public image5: string,
                public prix : number,
                public pricePromotion: string,
                public priceBasic : string,
                public quantite: number,
                public oldPrice: number,
                public newPrice: number,
                public discount: number,
                public ratingsCount: number,
                public rate: number,
                public description: string,
                public availibilityCount: number,
                public cartCount: number,
                public color: Array<string>,
                public size: Array<string>,
                public weight: number,
                public etat: string,
                public categorie: string,
                public contact: string,
                public user : string,
                public createdAt:string, 
                public updatedAt:string ){ }
  }