import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Customer } from 'src/app/models/customers.model';

export class CustomersData implements InMemoryDbService {
  createDb() {

  const customers: Customer[] = [
    {
      id: 1,
      nom: 'Dupont',
      prenom: 'Jean',
      adresse: '10 Rue de Paris, Paris, France',
      email: 'jean.dupont@example.com',
      numero: '+33 1 23 45 67 89',
      commande: 15,
      boutique: 'Boutique A',
      createdAt: '2023-01-15',
    },
    {
      id: 2,
      nom: 'Smith',
      prenom: 'Jane',
      adresse: '123 Main St, London, UK',
      email: 'jane.smith@example.co.uk',
      numero: '+44 20 7946 0958',
      commande: 8,
      boutique: 'Boutique B',
      createdAt: '2022-11-22',
    },
    {
      id: 3,
      nom: 'Garcia',
      prenom: 'Maria',
      adresse: 'Calle Mayor 5, Madrid, Spain',
      email: 'maria.garcia@example.es',
      numero: '+34 600 123 456',
      commande: 20,
      boutique: 'Boutique C',
      createdAt: '2023-05-10',
    },
    {
      id: 4,
      nom: 'Schmidt',
      prenom: 'Hans',
      adresse: 'Brandenburger Str. 12, Berlin, Germany',
      email: 'hans.schmidt@example.de',
      numero: '+49 30 12345678',
      commande: 5,
      boutique: 'Boutique D',
      createdAt: '2021-07-04',
    },
    {
      id: 5,
      nom: 'Rossi',
      prenom: 'Luca',
      adresse: 'Via Roma 25, Rome, Italy',
      email: 'luca.rossi@example.it',
      numero: '+39 06 1234 5678',
      commande: 12,
      boutique: 'Boutique A',
      createdAt: '2020-12-19',
    },
    {
      id: 6,
      nom: 'Kumar',
      prenom: 'Raj',
      adresse: 'B-12 Sector 5, Delhi, India',
      email: 'raj.kumar@example.in',
      numero: '+91 98765 43210',
      commande: 30,
      boutique: 'Boutique B',
      createdAt: '2022-03-01',
    },
    {
      id: 7,
      nom: 'Yamamoto',
      prenom: 'Takashi',
      adresse: '1-2-3 Ginza, Tokyo, Japan',
      email: 'takashi.yamamoto@example.jp',
      numero: '+81 3-1234-5678',
      commande: 18,
      boutique: 'Boutique C',
      createdAt: '2021-09-15',
    },
    {
      id: 8,
      nom: 'O’Connor',
      prenom: 'Liam',
      adresse: '45 Green Street, Dublin, Ireland',
      email: 'liam.oconnor@example.ie',
      numero: '+353 1 234 5678',
      commande: 10,
      boutique: 'Boutique D',
      createdAt: '2023-06-07',
    },
    {
      id: 9,
      nom: 'Chen',
      prenom: 'Wei',
      adresse: 'Building 5, Beijing, China',
      email: 'wei.chen@example.cn',
      numero: '+86 10 1234 5678',
      commande: 25,
      boutique: 'Boutique A',
      createdAt: '2023-02-21',
    },
    {
      id: 10,
      nom: 'Müller',
      prenom: 'Sofia',
      adresse: 'Bahnhofstr. 20, Zurich, Switzerland',
      email: 'sofia.mueller@example.ch',
      numero: '+41 44 123 45 67',
      commande: 6,
      boutique: 'Boutique B',
      createdAt: '2022-10-30',
    },
  ];

    return {customers};
  }
}
